name: Build and Release .EXE on version tag commit

on:
  push:
    tags:
      - "v*" # Trigger on version tags that start with 'v'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --name sdf_hud main.py
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }} # Use the Git tag as the release version
          release_name: Release ${{ github.ref }} # Use the Git tag for the release name
          body: "This release includes the executable file built from the tag ${{ github.ref }}."
          draft: false
          prerelease: false

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/sdf_hud.exe
          asset_name: sdf_hud.exe
          asset_content_type: application/octet-stream
