name: Build and Release .EXE on version tag commit

on:
  push:
    tags:
      - "v*" # Trigger on version tags that start with 'v'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build exe
        run: |
          pyinstaller --onefile --name sdf_hud main.py
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/sdf_hud.exe
